### PR TITLE
Fixed link to WebStorm doc page

### PR DESCRIPTION
**Pull request by martinduparc**

### CODE REVIEW

**Comment by Flet** [comment]
I'll update the build script to deal with this :/

**Comment by feross** [comment]
@Flet cool!

**Comment by Flet** [comment]
OK, with https://github.com/feross/standard-www/commit/dff68b8a0f2f706422bf6dfe79ae45b4605f82f7  things will now automatically generate correctly once feross/standard#454 gets merged. 

I went ahead and regenerated the site with a fixed webstorm.md and pushed it too.

**Comment by feross** [comment]
merged :)

**Pull request merged**
