### PR TITLE
Site design tweaks

### PR DESCRIPTION
**Pull request by feross**
Thoughts?

Before:

screen shot 2016-06-03 at 14 07 45

After:

screen shot 2016-06-03 at 14 07 39

Before:

screen shot 2016-06-03 at 14 07 57

After:

screen shot 2016-06-03 at 14 07 54

Before:

screen shot 2016-06-03 at 14 08 16

After:

screen shot 2016-06-03 at 14 08 14

### CODE REVIEW

**Comment by feross** [comment]
New font is Source Sans Pro, what I use in Sublime Text. Previous font was Latin Modern Roman, the LaTex default. I think it's a bit cleaner, but a slight but less authoritative. I think that's okay. Thoughts welcome, especially @Flet since you basically made most of the site.

**Comment by mafintosh** [comment]
i like the new font a bit better so 👍

**Comment by Flet** [comment]
I'm a fan of sans :) Looks like it matches the logo font too.

**Comment by Flet** [comment]
Added another change to remove the "center the first paragraph" style as it was making some pages look strange.

Also, I see that `contributing.html` is now being generated. Do you want this in the TOC too?

**Comment by feross** [comment]
The site is more for users of standard than for contributors, so I think it's fine to omit `contributing.html`, but I don't feel strongly.

**Comment by ungoldman** [comment]
lgtm sans-serif ftw

**Pull request merged**
